[tasks.docker-build]
command = "docker"
args = [
    "build",
    "-t",
    "{{repository}}/{{project-name}}:${CARGO_MAKE_CRATE_VERSION}",
    "-t",
    "{{repository}}/{{project-name}}:latest",
    ".",
]

[tasks.docker-run]
command = "docker"
args = [
    "run",
    "-it",
    "--rm",
    "{{repository}}/{{project-name}}:${CARGO_MAKE_CRATE_VERSION}",
]
dependencies = ["docker-build"]

[tasks.docker-push-versioned]
command = "docker"
args = ["push", "{{repository}}/{{project-name}}:${CARGO_MAKE_CRATE_VERSION}"]

[tasks.docker-push-latest]
command = "docker"
args = ["push", "{{repository}}/{{project-name}}:latest"]

[tasks.docker-publish]
dependencies = ["docker-build", "docker-push-versioned", "docker-push-latest"]
